import { useState, useEffect, useCallback } from "react";
import { ethers } from "ethers";

// Dynamic imports - generated by deploy script
const loadContracts = async () => {
  try {
    const [idrt, registry, payroll] = await Promise.all([
      import("../contracts/RupiahToken.json"),
      import("../contracts/ProjectRegistry.json"),
      import("../contracts/PayrollManager.json"),
    ]);
    return {
      RupiahToken:     idrt.default,
      ProjectRegistry: registry.default,
      PayrollManager:  payroll.default,
    };
  } catch {
    console.warn("⚠️  ABI belum ada. Jalankan deploy:local dulu.");
    return null;
  }
};

// ── Formatters ───────────────────────────────────────────────
export const formatRupiah = (val) => {
  if (val === undefined || val === null) return "—";
  const n = typeof val === "bigint" ? Number(val) : Number(val);
  return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(n);
};

export const formatDate = (ts) => {
  if (!ts || ts === 0n) return "—";
  return new Date(Number(ts) * 1000).toLocaleDateString("id-ID", {
    day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit"
  });
};

export const shortenAddr = (addr) =>
  addr ? `${addr.slice(0, 6)}...${addr.slice(-4)}` : "—";

export const TASK_STATUS_LABEL = ["OPEN","CLAIMED","SUBMITTED","APPROVED","COMPLETED","DISPUTED","CANCELLED"];
export const TASK_STATUS_CLASS = ["open","claimed","submitted","approved","completed","disputed","cancelled"];
export const PROJECT_STATUS_LABEL = ["AKTIF","DIJEDA","SELESAI","DIBATALKAN"];

// ── Main Hook ────────────────────────────────────────────────
export function useWeb3() {
  const [provider,   setProvider]   = useState(null);
  const [signer,     setSigner]     = useState(null);
  const [account,    setAccount]    = useState(null);
  const [chainId,    setChainId]    = useState(null);
  const [contracts,  setContracts]  = useState(null);  // { idrt, registry, payroll }
  const [balance,    setBalance]    = useState(0n);
  const [pmBudget,   setPmBudget]   = useState(0n);
  const [workerStats,setWorkerStats]= useState(null);
  const [isConnecting,setIsConnecting] = useState(false);
  const [error,      setError]      = useState(null);

  const initContracts = useCallback(async (signer, address) => {
    const abis = await loadContracts();
    if (!abis) { setError("Deploy kontrak dulu: cd blockchain && npm run deploy:local"); return; }

    const idrt     = new ethers.Contract(abis.RupiahToken.address,     abis.RupiahToken.abi,     signer);
    const registry = new ethers.Contract(abis.ProjectRegistry.address, abis.ProjectRegistry.abi, signer);
    const payroll  = new ethers.Contract(abis.PayrollManager.address,   abis.PayrollManager.abi,  signer);

    setContracts({ idrt, registry, payroll });

    const [bal, budget, stats] = await Promise.all([
      idrt.balanceOf(address),
      payroll.getPMBudget(address),
      payroll.getWorkerStats(address),
    ]);
    setBalance(bal);
    setPmBudget(budget);
    setWorkerStats(stats);
  }, []);

  const refreshBalance = useCallback(async (address) => {
    if (!contracts || !address) return;
    const [bal, budget, stats] = await Promise.all([
      contracts.idrt.balanceOf(address),
      contracts.payroll.getPMBudget(address),
      contracts.payroll.getWorkerStats(address),
    ]);
    setBalance(bal);
    setPmBudget(budget);
    setWorkerStats(stats);
  }, [contracts]);

  const connect = useCallback(async () => {
    if (!window.ethereum) { setError("MetaMask tidak ditemukan!"); return; }
    setIsConnecting(true);
    setError(null);
    try {
      const _provider = new ethers.BrowserProvider(window.ethereum);
      await _provider.send("eth_requestAccounts", []);
      const _signer  = await _provider.getSigner();
      const _account = await _signer.getAddress();
      const network  = await _provider.getNetwork();
      setProvider(_provider);
      setSigner(_signer);
      setAccount(_account);
      setChainId(Number(network.chainId));
      await initContracts(_signer, _account);
    } catch (err) {
      setError(err.message);
    } finally {
      setIsConnecting(false);
    }
  }, [initContracts]);

  const disconnect = useCallback(() => {
    setProvider(null); setSigner(null); setAccount(null);
    setChainId(null);  setContracts(null); setBalance(0n);
    setPmBudget(0n);   setWorkerStats(null);
  }, []);

  useEffect(() => {
    if (!window.ethereum) return;
    const onAccount = (accs) => { if (accs.length === 0) disconnect(); else window.location.reload(); };
    const onChain   = () => window.location.reload();
    window.ethereum.on("accountsChanged", onAccount);
    window.ethereum.on("chainChanged",    onChain);
    return () => {
      window.ethereum.removeListener("accountsChanged", onAccount);
      window.ethereum.removeListener("chainChanged",    onChain);
    };
  }, [disconnect]);

  return {
    provider, signer, account, chainId,
    contracts, balance, pmBudget, workerStats,
    isConnecting, error,
    connect, disconnect, refreshBalance,
    isConnected: !!account,
    shortAddress: account ? shortenAddr(account) : null,
    networkName: { 31337: "Hardhat Local", 80001: "Mumbai Testnet", 137: "Polygon Mainnet" }[chainId] || `Chain ${chainId}`,
  };
}
